// <auto-generated />
using FutScore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutScore.Data.Migrations
{
    [DbContext(typeof(FutScoreDbContext))]
    [Migration("20250705224912_PopulandoBancoDeDados")]
    partial class PopulandoBancoDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutScore.Modelos.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cariocão"
                        });
                });

            modelBuilder.Entity("FutScore.Modelos.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gols")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Jogadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gols = 0,
                            Nome = "Paulinho",
                            Posicao = 3,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Gols = 0,
                            Nome = "Coutinho",
                            Posicao = 4,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Gols = 0,
                            Nome = "Vegetti",
                            Posicao = 6,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Gols = 0,
                            Nome = "Léo Jardim",
                            Posicao = 0,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Gols = 0,
                            Nome = "João Victor",
                            Posicao = 1,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Gols = 0,
                            Nome = "Nuno",
                            Posicao = 5,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Gols = 0,
                            Nome = "David",
                            Posicao = 5,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Gols = 0,
                            Nome = "Sforza",
                            Posicao = 3,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Gols = 0,
                            Nome = "Lucas Freitas",
                            Posicao = 1,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Gols = 0,
                            Nome = "Lucas Piton",
                            Posicao = 2,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Gols = 0,
                            Nome = "Paulo Henrique",
                            Posicao = 2,
                            TimeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Gols = 0,
                            Nome = "Arrascaeta",
                            Posicao = 4,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Gols = 0,
                            Nome = "Pedro",
                            Posicao = 6,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Gols = 0,
                            Nome = "Pulgar",
                            Posicao = 3,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Gols = 0,
                            Nome = "Cebolinha",
                            Posicao = 5,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Gols = 0,
                            Nome = "Nico De La Cruz",
                            Posicao = 5,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 17,
                            Gols = 0,
                            Nome = "Léo Ortiz",
                            Posicao = 1,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Gols = 0,
                            Nome = "Léo Pereira",
                            Posicao = 1,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Gols = 0,
                            Nome = "Gerson",
                            Posicao = 4,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Gols = 0,
                            Nome = "Wesley",
                            Posicao = 2,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Gols = 0,
                            Nome = "Ayrton Lucas",
                            Posicao = 2,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 22,
                            Gols = 0,
                            Nome = "Rossi",
                            Posicao = 0,
                            TimeId = 2
                        },
                        new
                        {
                            Id = 23,
                            Gols = 0,
                            Nome = "John",
                            Posicao = 0,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 24,
                            Gols = 0,
                            Nome = "Damián Suárez",
                            Posicao = 2,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 25,
                            Gols = 0,
                            Nome = "Bastos",
                            Posicao = 1,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 26,
                            Gols = 0,
                            Nome = "Lucas Halter",
                            Posicao = 1,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 27,
                            Gols = 0,
                            Nome = "Cuiabano",
                            Posicao = 2,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 28,
                            Gols = 0,
                            Nome = "Marlon Freitas",
                            Posicao = 3,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 29,
                            Gols = 0,
                            Nome = "Danilo Barbosa",
                            Posicao = 3,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Gols = 0,
                            Nome = "Luiz Henrique",
                            Posicao = 5,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 31,
                            Gols = 0,
                            Nome = "Júnior Santos",
                            Posicao = 5,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 32,
                            Gols = 0,
                            Nome = "Tiquinho Soares",
                            Posicao = 6,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 33,
                            Gols = 0,
                            Nome = "Eduardo",
                            Posicao = 4,
                            TimeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Gols = 0,
                            Nome = "Fábio",
                            Posicao = 0,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 35,
                            Gols = 0,
                            Nome = "Samuel Xavier",
                            Posicao = 2,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 36,
                            Gols = 0,
                            Nome = "Felipe Melo",
                            Posicao = 1,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 37,
                            Gols = 0,
                            Nome = "Marlon",
                            Posicao = 1,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 38,
                            Gols = 0,
                            Nome = "Marcelo",
                            Posicao = 2,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 39,
                            Gols = 0,
                            Nome = "André",
                            Posicao = 3,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 40,
                            Gols = 0,
                            Nome = "Martinelli",
                            Posicao = 3,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 41,
                            Gols = 0,
                            Nome = "Ganso",
                            Posicao = 4,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 42,
                            Gols = 0,
                            Nome = "Jhon Arias",
                            Posicao = 4,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 43,
                            Gols = 0,
                            Nome = "Keno",
                            Posicao = 5,
                            TimeId = 4
                        },
                        new
                        {
                            Id = 44,
                            Gols = 0,
                            Nome = "Germán Cano",
                            Posicao = 6,
                            TimeId = 4
                        });
                });

            modelBuilder.Entity("FutScore.Modelos.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<int>("CasaId")
                        .HasColumnType("int");

                    b.Property<int>("ForaId")
                        .HasColumnType("int");

                    b.Property<int>("GolsCasa")
                        .HasColumnType("int");

                    b.Property<int>("GolsFora")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("CasaId");

                    b.HasIndex("ForaId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("FutScore.Modelos.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<int>("GolsContra")
                        .HasColumnType("int");

                    b.Property<int>("GolsPro")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("SaldoDeGols")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampeonatoId = 1,
                            Forca = 60,
                            GolsContra = 0,
                            GolsPro = 0,
                            Nome = "Vasco",
                            Pontuacao = 0,
                            SaldoDeGols = 0
                        },
                        new
                        {
                            Id = 2,
                            CampeonatoId = 1,
                            Forca = 70,
                            GolsContra = 0,
                            GolsPro = 0,
                            Nome = "Flamengo",
                            Pontuacao = 0,
                            SaldoDeGols = 0
                        },
                        new
                        {
                            Id = 3,
                            CampeonatoId = 1,
                            Forca = 65,
                            GolsContra = 0,
                            GolsPro = 0,
                            Nome = "Botafogo",
                            Pontuacao = 0,
                            SaldoDeGols = 0
                        },
                        new
                        {
                            Id = 4,
                            CampeonatoId = 1,
                            Forca = 68,
                            GolsContra = 0,
                            GolsPro = 0,
                            Nome = "Fluminense",
                            Pontuacao = 0,
                            SaldoDeGols = 0
                        });
                });

            modelBuilder.Entity("FutScore.Modelos.Jogador", b =>
                {
                    b.HasOne("FutScore.Modelos.Time", "Time")
                        .WithMany("Elenco")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("FutScore.Modelos.Partida", b =>
                {
                    b.HasOne("FutScore.Modelos.Campeonato", "Campeonato")
                        .WithMany("Partidas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutScore.Modelos.Time", "Casa")
                        .WithMany()
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutScore.Modelos.Time", "Fora")
                        .WithMany()
                        .HasForeignKey("ForaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Casa");

                    b.Navigation("Fora");
                });

            modelBuilder.Entity("FutScore.Modelos.Time", b =>
                {
                    b.HasOne("FutScore.Modelos.Campeonato", "Campeonato")
                        .WithMany("Times")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("FutScore.Modelos.Campeonato", b =>
                {
                    b.Navigation("Partidas");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("FutScore.Modelos.Time", b =>
                {
                    b.Navigation("Elenco");
                });
#pragma warning restore 612, 618
        }
    }
}
